(()=>{const root=document.querySelector("[data-mini-games]");if(!root)return;
const lang=document.documentElement.lang==="es"?"es":"en";
const t=lang==="es"?{
back:"← juegos",playAgain:"jugar de nuevo",shuffle:"mezclar de nuevo",memory:"memoria Moth",catch:"atrapa luciérnagas",count:"cuenta luciérnagas",lantern:"farol Moth",follow:"sigue a Moth",forage:"busca hongos",
memoryDesc:"Encuentra las cuatro parejas.",catchDesc:"Atrapa las seis luciérnagas.",countDesc:"Mira bien y recuerda cuántas viste.",lanternDesc:"Guía cinco luciérnagas hasta el farol.",followDesc:"Mira dónde se esconde Moth y luego encuéntralo.",forageDesc:"Encuentra los tres hongos escondidos.",
caught:n=>`${n} de 6 luciérnagas atrapadas`,allCaught:"¡las atrapaste todas!",countReady:"¿cuántas viste?",countCorrect:"¡sí! eran ",countWrong:n=>"casi. eran "+n+".",lanternProgress:n=>`${n} de 5 luciérnagas llegaron al farol`,lanternDone:"el farol está encendido.",followWatch:"mira bien...",followPick:"¿dónde está Moth?",followCorrect:"¡lo encontraste!",followWrong:"no estaba ahí. prueba de nuevo.",forageProgress:n=>`${n} de 3 hongos encontrados`,forageDone:"¡encontraste los tres!",
hidden:"Tarjeta oculta ",revealed:"Tarjeta revelada",matched:" emparejada",pairs:n=>n===4?"las cuatro encontradas":n+" de 4 parejas encontradas"
}:{
back:"← games",playAgain:"play again",shuffle:"shuffle again",memory:"moth memory",catch:"catch fireflies",count:"firefly count",lantern:"moth lantern",follow:"follow Moth",forage:"mushroom forage",
memoryDesc:"Find the four matching pairs.",catchDesc:"Catch all six fireflies.",countDesc:"Watch closely and remember how many you saw.",lanternDesc:"Guide five fireflies into the lantern.",followDesc:"Watch where Moth hides, then find it.",forageDesc:"Find the three hidden mushrooms.",
caught:n=>`${n} of 6 fireflies caught`,allCaught:"you caught them all!",countReady:"how many did you see?",countCorrect:"yes! there were ",countWrong:n=>"almost. there were "+n+".",lanternProgress:n=>`${n} of 5 fireflies reached the lantern`,lanternDone:"the lantern is glowing.",followWatch:"watch closely...",followPick:"where is Moth?",followCorrect:"you found Moth!",followWrong:"not there. try again.",forageProgress:n=>`${n} of 3 mushrooms found`,forageDone:"you found all three!",
hidden:"Hidden memory card ",revealed:"Revealed memory card",matched:" matched",pairs:n=>n===4?"all four found":n+" of 4 pairs found"
};
const assets={
moon:"/assets/decor-moon.webp?v=1",stars:"/assets/game-decor-stars.webp?v=1",fireflies:"/assets/moth-fireflies-final.webp?v=1",lantern:"/assets/moth-lantern-final.webp?v=1",moth:"/assets/moth-icon-final.webp?v=2",fern:"/assets/game-decor-fern.webp?v=1",mush:"/assets/game-decor-mushrooms.webp?v=1",
seasonal:{
spring:["/assets/memory/spring-wild-violet.webp?v=1","/assets/memory/spring-fiddlehead-fern.webp?v=1","/assets/memory/spring-morel.webp?v=1"],
summer:["/assets/memory/summer-mulberry.webp?v=1","/assets/memory/summer-yarrow.webp?v=1","/assets/memory/summer-indigo-milk-cap.webp?v=1"],
fall:["/assets/memory/fall-maple-leaf.webp?v=1","/assets/memory/fall-persimmon.webp?v=1","/assets/memory/fall-devils-cigar.webp?v=1"],
winter:["/assets/memory/winter-pinecone.webp?v=1","/assets/memory/winter-winterberry.webp?v=1","/assets/memory/winter-hair-ice.webp?v=1"]
}};
const month=new Date().getMonth(),season=month>=2&&month<=4?"spring":month>=5&&month<=7?"summer":month>=8&&month<=10?"fall":"winter";
const picker=root.querySelector(".game-picker"),stage=root.querySelector(".mini-game-stage"),title=stage.querySelector(".mini-game-title"),desc=stage.querySelector(".mini-game-desc"),body=stage.querySelector(".mini-game-body"),status=stage.querySelector(".mini-game-status"),back=stage.querySelector(".mini-game-back"),action=stage.querySelector(".mini-game-action");
let cleanup=()=>{};
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const showPicker=()=>{cleanup();cleanup=()=>{};stage.hidden=true;picker.hidden=false;status.textContent="";body.innerHTML="";action.hidden=true};
const open=(name)=>{cleanup();cleanup=()=>{};picker.hidden=true;stage.hidden=false;action.hidden=false;const fn=games[name];if(fn)fn()};
back.addEventListener("click",showPicker);picker.addEventListener("click",e=>{const b=e.target.closest("[data-game]");if(b)open(b.dataset.game)});

const memoryData=()=>{const p=lang==="es"?[["lantern",assets.lantern,"Farol"],["moon",assets.moon,"Luna"],["fireflies",assets.fireflies,"Luciérnagas"]]:[["lantern",assets.lantern,"Lantern"],["moon",assets.moon,"Moon"],["fireflies",assets.fireflies,"Fireflies"]];
const labels=lang==="es"?{spring:["Violeta silvestre","Brotes de helecho","Colmenilla"],summer:["Moras de morera","Milenrama","Hongo índigo"],fall:["Hoja de arce","Caqui americano","Cigarro del diablo"],winter:["Piña de pino","Bayas de invierno","Hielo filamentoso"]}:{spring:["Wild violet","Fiddlehead fern","Morel mushroom"],summer:["Mulberry","Yarrow","Indigo milk cap"],fall:["Maple leaf","American persimmon","Devil's cigar fungus"],winter:["Pinecone","Winterberry","Hair ice"]};
return [...p,...assets.seasonal[season].map((src,i)=>[season+"-"+i,src,labels[season][i]])]};

const games={
memory(){title.textContent=t.memory;desc.textContent=t.memoryDesc;action.textContent=t.shuffle;body.innerHTML='<div class="game-wrap"><div class="game-grid" role="group"></div><div class="game-meta"><span class="memory-status" role="status" aria-live="polite"></span></div></div>';const grid=body.querySelector(".game-grid"),ms=body.querySelector(".memory-status");let openCards=[],locking=false,found=0,last="",token=0,timer=null;const data=memoryData();const reset=()=>{token++;if(timer)clearTimeout(timer);openCards=[];locking=false;found=0;ms.textContent=t.pairs(0);grid.innerHTML="";let chosen,key;do{chosen=shuffle([...data]).slice(0,4);key=chosen.map(x=>x[0]).sort().join("|")}while(key===last&&data.length>4);last=key;shuffle([...chosen,...chosen].map((x,i)=>[...x,i+"-"+Math.random()])).forEach((x,i)=>{const b=document.createElement("button");b.type="button";b.className="memory-card";b.dataset.id=x[0];b.dataset.alt=x[2];b.dataset.position=String(i+1);b.setAttribute("aria-label",t.hidden+(i+1));b.setAttribute("aria-pressed","false");b.innerHTML='<span class="memory-inner"><span class="memory-face memory-back" aria-hidden="true"><img draggable="false" class="memory-back-star" src="/assets/christmas-star.webp?v=2" alt=""></span><span class="memory-face memory-front"><img draggable="false" src="'+x[1]+'" alt=""></span></span>';b.addEventListener("click",()=>flip(b));grid.appendChild(b)})};const flip=c=>{if(locking||c.classList.contains("open")||c.classList.contains("matched"))return;c.classList.add("open");c.setAttribute("aria-label",c.dataset.alt||t.revealed);c.setAttribute("aria-pressed","true");openCards.push(c);if(openCards.length<2)return;const[a,b]=openCards;if(a.dataset.id===b.dataset.id){[a,b].forEach(x=>{x.classList.add("matched");x.classList.remove("open");x.disabled=true;x.setAttribute("aria-label",x.dataset.alt+t.matched)});openCards=[];found++;ms.textContent=t.pairs(found);return}locking=true;const mine=token;timer=setTimeout(()=>{if(mine!==token)return;[a,b].forEach(x=>{x.classList.remove("open");x.setAttribute("aria-label",t.hidden+x.dataset.position);x.setAttribute("aria-pressed","false")});openCards=[];locking=false;timer=null},650)};action.onclick=reset;reset();cleanup=()=>{token++;if(timer)clearTimeout(timer)}},
catch(){title.textContent=t.catch;desc.textContent=t.catchDesc;action.textContent=t.playAgain;body.innerHTML='<div class="firefly-field catch-field"></div>';const field=body.firstElementChild;let caught=0;const start=()=>{caught=0;status.textContent=t.caught(0);field.innerHTML="";const spots=shuffle([[16,22],[42,18],[74,27],[24,62],[52,70],[81,61]]);for(let i=0;i<6;i++){const b=document.createElement("button");b.type="button";b.className="mini-firefly";b.style.left=(spots[i][0]+(Math.random()*6-3))+"%";b.style.top=(spots[i][1]+(Math.random()*6-3))+"%";b.style.setProperty("--dur",(3.1+Math.random()*2)+"s");b.style.setProperty("--delay",(-Math.random()*2)+"s");b.setAttribute("aria-label",lang==="es"?"atrapar luciérnaga":"catch firefly");b.innerHTML='<span aria-hidden="true"></span>';b.onclick=()=>{if(b.classList.contains("caught"))return;b.classList.add("caught");b.disabled=true;caught++;status.textContent=caught===6?t.allCaught:t.caught(caught)};field.appendChild(b)}};action.onclick=start;start()},
count(){title.textContent=t.count;desc.textContent=t.countDesc;action.textContent=t.playAgain;body.innerHTML='<div class="firefly-field count-field"></div><div class="count-answers"></div>';const field=body.querySelector(".count-field"),answers=body.querySelector(".count-answers");let answer=0,timer=null;const start=()=>{if(timer)clearTimeout(timer);answer=3+Math.floor(Math.random()*5);status.textContent="";field.classList.remove("is-hidden");field.innerHTML="";answers.innerHTML="";for(let i=0;i<answer;i++){const d=document.createElement("span");d.className="count-dot";d.style.left=(12+Math.random()*76)+"%";d.style.top=(14+Math.random()*70)+"%";field.appendChild(d)};timer=setTimeout(()=>{field.classList.add("is-hidden");status.textContent=t.countReady;for(let n=3;n<=7;n++){const b=document.createElement("button");b.type="button";b.className="count-answer";b.textContent=n;b.onclick=()=>{answers.querySelectorAll("button").forEach(x=>x.disabled=true);status.textContent=n===answer?t.countCorrect+answer+"!":t.countWrong(answer)};answers.appendChild(b)}},1250)};action.onclick=start;start();cleanup=()=>{if(timer)clearTimeout(timer)}},
lantern(){title.textContent=t.lantern;desc.textContent=t.lanternDesc;action.textContent=t.playAgain;body.innerHTML='<div class="lantern-game-field"><div class="lantern-game-lamp"><span class="lantern-game-glow"></span><img src="'+assets.lantern+'" alt=""></div></div>';const field=body.firstElementChild,glow=field.querySelector(".lantern-game-glow");let guided=0;const start=()=>{guided=0;field.classList.remove("complete");glow.style.opacity=".13";glow.style.transform="scale(.85)";field.querySelectorAll(".mini-firefly").forEach(x=>x.remove());status.textContent=t.lanternProgress(0);const spots=shuffle([[13,20],[84,22],[16,74],[83,72],[50,14]]);for(let i=0;i<5;i++){const b=document.createElement("button");b.type="button";b.className="mini-firefly";b.style.left=(spots[i][0]+(Math.random()*4-2))+"%";b.style.top=(spots[i][1]+(Math.random()*4-2))+"%";b.setAttribute("aria-label",lang==="es"?"guiar luciérnaga al farol":"guide firefly to lantern");b.innerHTML='<span aria-hidden="true"></span>';b.onclick=()=>{b.disabled=true;b.classList.add("caught");guided++;glow.style.opacity=String(.13+guided*.13);glow.style.transform="scale("+(0.85+guided*.06)+")";status.textContent=guided===5?t.lanternDone:t.lanternProgress(guided);if(guided===5)field.classList.add("complete")};field.appendChild(b)}};action.onclick=start;start()},
follow(){title.textContent=t.follow;desc.textContent=t.followDesc;action.textContent=t.playAgain;body.innerHTML='<div class="follow-board"></div>';const board=body.firstElementChild;let canPick=false,timers=[];const plants=[assets.fern,assets.mush,assets.seasonal[season][1]];const clear=()=>{timers.forEach(clearTimeout);timers=[]};const start=()=>{clear();canPick=false;status.textContent=t.followWatch;board.innerHTML="";const target=Math.floor(Math.random()*3),buttons=[];for(let i=0;i<3;i++){const b=document.createElement("button");b.type="button";b.className="moth-cover"+(i===target?" peek":"");b.dataset.target=String(i===target);b.setAttribute("aria-label",(lang==="es"?"escondite ":"hiding place ")+(i+1));b.innerHTML='<img class="peek-moth" src="'+assets.moth+'" alt=""><img class="cover-plant" src="'+plants[i]+'" alt="">';b.onclick=()=>{if(!canPick)return;canPick=false;const targetButton=buttons.find(x=>x.dataset.target==="true");if(b.dataset.target==="true"){b.classList.add("correct","peek");status.textContent=t.followCorrect}else{b.classList.add("wrong");targetButton.classList.add("correct","peek");status.textContent=t.followWrong}};buttons.push(b);board.appendChild(b)};timers.push(setTimeout(()=>{buttons.find(x=>x.dataset.target==="true").classList.remove("peek");let swaps=0;const swap=()=>{const current=[...board.children],a=swaps%2,b=(swaps+1)%3;board.insertBefore(current[b],current[a]);swaps++;if(swaps<4)timers.push(setTimeout(swap,260));else{status.textContent=t.followPick;canPick=true}};swap()},1050))};action.onclick=start;start();cleanup=clear},
forage(){title.textContent=t.forage;desc.textContent=t.forageDesc;action.textContent=t.playAgain;body.innerHTML='<div class="forage-grid"></div>';const grid=body.firstElementChild;let found=0;const start=()=>{found=0;status.textContent=t.forageProgress(0);grid.innerHTML="";const hits=new Set(shuffle([0,1,2,3,4,5]).slice(0,3));for(let i=0;i<6;i++){const b=document.createElement("button");b.type="button";b.className="forage-patch";b.setAttribute("aria-label",(lang==="es"?"buscar en el rincón ":"search patch ")+(i+1));const cover=i%2===0?assets.fern:assets.seasonal[season][i%3];b.innerHTML='<img class="forage-cover" src="'+cover+'" alt=""><img class="forage-find" src="'+assets.mush+'" alt="">';b.onclick=()=>{if(b.disabled)return;b.disabled=true;if(hits.has(i)){b.classList.add("found");found++;status.textContent=found===3?t.forageDone:t.forageProgress(found)}else{b.classList.add("empty")}};grid.appendChild(b)}};action.onclick=start;start()}
};
showPicker();
})();